name: Auto Update

on:
  #schedule:
    #- cron:  '*/20 * * * *'
  push:
    branches: [ master ]

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Check stage for this content
        run: git ls-files --stage
        
      #- name: Backtrace rights
        #run: git update-index --chmod=+x './bin/update-sources.sh'
 
      - name: Reserve Right Update Sources
        run: ./bin/update-sources.sh
  
      - name: Commit Sources Data
        run: |
          if git diff --name-only covid19/data-sources/*.csv | grep . ; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "update sources data" covid19/data-sources/*.csv
          fi
  
      - name: Build Viz Data
        run: ./bin/export-main-countries.py
  
      - name: Commit & Push Viz Data
        run: |
          if git diff --name-only covid19/data-sources/*.json | grep . > /dev/null ; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "update viz data" covid19/data-sources/coronavirus-countries.json
            git push
          fi
  
