on: 
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@master
    - name: Build the data and create local changes
      uses: actions/setup-python@v1
      with:
        python-version: '3.6.11'
        architecture: x64
    - name: Install requirements
      run: |
        pip install -r covid19/requirements.txt
    - name: Process Data
      run: |
        python covid19/world.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "Auto-update of the data packages" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gh }}
  deploy:
    needs: update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - run: npm install -g data-cli
    - run: data --version
    - run: data push
      env:
        id: ${{secrets.dhid}}
        username: ${{secrets.dhusername}}
        token: ${{secrets.dhtoken}}
