name: Data Refresh

on: [push]
  #schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '0 */6 * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: macos-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install pandoc 
        run: |
          #sudo apt-get update && sudo apt-get install pandoc
          brew install pandoc
          #brew install pandoc-citeproc
      - name: Install leafpop
        run: Rscript -e "install.packages(c('leafpop', type = 'source'))"
      - name: Test leafpop
        run: Rscript -e  "?leafpop::popupTable"
      - name: Install leaflet
        run: Rscript -e "install.packages(c('leaflet'))"
      - name: Install mapview
        run: Rscript -e "install.packages(c('mapview'))"
      - name: Install CRAN packages
        run: Rscript -e "install.packages(c('devtools', 'rmarkdown', 'flexdashboard', 'dplyr', 'purrr', 'lubridate', 'plotly'))"
      - name: Install Github packages
        run: Rscript -e "devtools::install_github('Covid19R/covid19Italy')" -e "devtools::install_github('Covid19R/coronavirus')"
      - name: Render the site
        run: Rscript -e "rmarkdown::render_site()"
      #- name: Push updates  
      #  if: success()
      #  run: |
      #    if [[ "$(git status --porcelain)" != "" ]]; then
      #        git config --global user.name 'RamiKrispin'
      #        git config --global user.email 'ramkrisp@umich.edu'
      #        git commit -am "Update italy province data"
      #        git push
      #    fi
      
